### PR TITLE
Fix scroll depending animations due to wrong scroll listener

### LINKED ISSUE #428: Bug: Pictures are not always visible in Themes section
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Description

Images in the `Themes` section are not always visible.
I can't see them using Chrome, Firefox, Edge, Chrome Mobile (Desktop Version toggled)
I can see them using Firefox Mobile (Desktop Version toggled)
I tested with two different Internet connections

### Steps To Reproduce

1. Open the site
2. Scroll down to `Themes` section
3. See that the pictures on the right are missing

### Expected behavior

The images on the right of the `Themes` section should be displayed

### Relevant Assets

image

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Since the scrolling is not done on the window but rather the body, listening to window scroll events does not work. We fix this by listening to the body element for the scroll events.

## Motivation and Context

Closes #428

### CODE REVIEW

File: src/layout/DesignSection/DesignSection.svelte [hunk 1]
```diff
@@ -1,14 +1,17 @@
...
-<svelte:window
-	on:scroll={() =>
-		window.requestAnimationFrame(() => (scrollY = window.scrollY))}
-/>
+	onMount(() => {
+		const body = document.getElementsByTagName("body")[0];
+		body.addEventListener("scroll", () => {
+			scrollY = body.scrollTop;
+		});
+	});
```
Comment (TheOnlyTails) [inline src/layout/DesignSection/DesignSection.svelte:13]: Since you're using `onMount` here, you should return a function to be called when the component is destroyed, like so:


```suggestion
	onMount(() => {
		const body = document.getElementsByTagName("body")[0];
    const handleScroll = () => {
			scrollY = body.scrollTop;
		}
		body.addEventListener("scroll", handleScroll);

    return () => body.removeEventListener("scroll", handleScroll)
	});
```

the docs for the `removeEventListener` function are available here: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener

File: src/layout/ThemesSection/ThemesSection.svelte [hunk 2]
```diff
@@ -67,10 +67,15 @@
 			.addEventListener("change", e => {
 				systemTheme = e.matches ? "dark" : "light";
 			});
+
+		const body = document.getElementsByTagName("body")[0];
+		body.addEventListener("scroll", () => {
+			scrollY = body.scrollTop;
+		});
```
Comment (TheOnlyTails) [inline src/layout/ThemesSection/ThemesSection.svelte:74]:
```suggestion
		const body = document.getElementsByTagName("body")[0];
    const handleScroll = () => {
			scrollY = body.scrollTop;
		}
		body.addEventListener("scroll", handleScroll);

    return () => body.removeEventListener("scroll", handleScroll)
```

**Review by TheOnlyTails — CHANGES_REQUESTED** [review]
events registered in `onMount` should be removed when the component is destroyed

**Review by TheOnlyTails — CHANGES_REQUESTED** [review]
Never mind, i just realized - you can use `on:scroll` for on the [`<svelte:body>`](https://svelte.dev/docs#template-syntax-svelte-body) element, which is a much more elegant solution.

File: src/layout/DesignSection/DesignSection.svelte (hunk 1 above)
Comment (chingucoding) [reply src/layout/DesignSection/DesignSection.svelte]: Should we also remove the event listener for the theme change event in that componenet when it gets destroyed?

**Review by TheOnlyTails — APPROVED** [review]

File: src/layout/DesignSection/DesignSection.svelte (hunk 1 above)
Comment (TheOnlyTails) [reply src/layout/DesignSection/DesignSection.svelte]: Yeah, sure. it won't make too much of a difference, but it's probably better convention.

File: src/layout/ThemesSection/ThemesSection.svelte [hunk 3]
```diff
@@ -50,11 +51,17 @@
...
+			anchor.offsetHeight / 4 +
+			scrollPositionY <
+			scrollPositionY + innerHeight
 	)
 		visible = true;
 
+	const handleThemeChange = (e: MediaQueryListEvent) => {
+		systemTheme = e.matches ? "dark" : "light";
+	};
+
```
Comment (TheOnlyTails) [inline src/layout/ThemesSection/ThemesSection.svelte:64]: could you move this inside `onMount`?

**Review by TheOnlyTails — APPROVED** [review]
